<%doc>
   Component: auth_check_directory.comp
        Date: 9/2/2002
      Author: allan
 Description: checks if the user has access to edit directory, returns 0 or 1
</%doc>

<%args>
</%args>

<%init>
my $auth = $m->comp('/mason/auth/auth_check.comp',auth_type=>'events');
my $sysadm = $m->comp('/mason/auth/auth_check.comp',auth_type=>'sysadm');
</%init>

<%perl>
return $auth || $sysadm;
</%perl>
